### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by the-lost-explorer** [ai-vithink/ai-vithink.github.io#1]
@dwij2812  I need the forum logo. Can you request ma'am please! Put it under /img folder in this repo.

**Comment by dwij2812** [comment]
![untitled](https://user-images.githubusercontent.com/29058310/43133465-7d00cad2-8f5c-11e8-89b0-26d536db88b2.png)

**Check This Out!**

Vector Image can be found in the /img folder in this repo
